package com.deepika.list_test_rm_proj_singlefire;

import java.util.*;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class combined_pojo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public combined_pojo() {
    }
    
    private java.util.List<java.lang.String> UDC = new ArrayList<String>();
    private java.lang.String strVal;
	public java.lang.String getStrVal() {
		return this.strVal;
	}

	public void setStrVal(java.lang.String strVal) {
		this.strVal = strVal;
	}



public java.util.List<java.lang.String> getUDC() {
		return this.UDC;
	}

	public void setUDC(java.lang.String input) {
	   //if(UDC.size() != 0){
	   //     UDC.removeAll(UDC);
	     //   this.UDC.add(input);
	   // }else{
			this.UDC.add(input);
	  //  }
	}



private java.util.List<java.lang.String> UDC1 = new ArrayList<String>();


	public java.util.List<java.lang.String> getUDC1() {
		return this.UDC1;
	}

	public void setUDC1(java.lang.String input) {
			UDC1.add(input);
	}
	

}